version: "3.9"

services:

  mongo1:
    image: "mongo:4.4.18"
    container_name: "mongo1"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
    volumes:
      - mongo1_data:/data/db
      - ./mongod.conf:/etc/mongod.conf:ro
      - ./mongo-keyfile:/etc/mongo/keyfile:ro
    command:
      [
        "bash", "-c",
        "chown mongodb:mongodb /etc/mongo/keyfile && chmod 400 /etc/mongo/keyfile && exec mongod --config /etc/mongod.conf --replSet rs0 --keyFile /etc/mongo/keyfile"
      ]
    networks:
      - mongo-net

  mongo2:
    image: "mongo:4.4.18"
    container_name: "mongo2"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
    volumes:
      - mongo2_data:/data/db
      - ./mongod.conf:/etc/mongod.conf:ro
      - ./mongo-keyfile:/etc/mongo/keyfile:ro
    command:
      [
        "bash", "-c",
        "chown mongodb:mongodb /etc/mongo/keyfile && chmod 400 /etc/mongo/keyfile && exec mongod --config /etc/mongod.conf --replSet rs0 --keyFile /etc/mongo/keyfile"
      ]
    networks:
      - mongo-net

  mongo3:
    image: "mongo:4.4.18"
    container_name: "mongo3"
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
    volumes:
      - mongo3_data:/data/db
      - ./mongod.conf:/etc/mongod.conf:ro
      - ./mongo-keyfile:/etc/mongo/keyfile:ro
    command:
      [
        "bash", "-c",
        "chown mongodb:mongodb /etc/mongo/keyfile && chmod 400 /etc/mongo/keyfile && exec mongod --config /etc/mongod.conf --replSet rs0 --keyFile /etc/mongo/keyfile"
      ]
    networks:
      - mongo-net

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:

networks:
  mongo-net:
    driver: bridge
