version: "3.9"

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      MONGO_INITDB_DATABASE: admin
    volumes:
      - mongo_data:/data/db
      - ./mongod.conf:/etc/mongod.conf:ro
      - ./init/:/docker-entrypoint-initdb.d:ro
      - ./keyfile:/etc/mongo/keyfile:ro
    command: ["mongod", "--replSet", "rs0", "--auth", "--keyFile", "/etc/mongo/keyfile", "--config", "/etc/mongod.conf"]
    networks:
      - shared-net

  mongodb2:
    image: mongo:4.4
    container_name: mongodb2
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      MONGO_INITDB_DATABASE: admin
    volumes:
      - mongo_data:/data/db
      - ./mongod.conf:/etc/mongod.conf:ro
      - ./init/:/docker-entrypoint-initdb.d:ro
      - ./keyfile:/etc/mongo/keyfile:ro
    command: ["mongod", "--replSet", "rs0", "--auth", "--keyFile", "/etc/mongo/keyfile", "--config", "/etc/mongod.conf"]
    networks:
      - shared-net

  mongodb3:
    image: mongo:4.4
    container_name: mongodb3
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASS}
      MONGO_INITDB_DATABASE: admin
    volumes:
      - mongo_data:/data/db
      - ./mongod.conf:/etc/mongod.conf:ro
      - ./init/:/docker-entrypoint-initdb.d:ro
      - ./keyfile:/etc/mongo/keyfile:ro
    command: ["mongod", "--replSet", "rs0", "--auth", "--keyFile", "/etc/mongo/keyfile", "--config", "/etc/mongod.conf"]
    networks:
      - shared-net

volumes:
  mongo_data:

networks:
  shared-net:
    external: true
